// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8iuVfDg2qRQcBp6q1v9e7ggY9JiSmfY',
    appId: '1:285312235143:web:8fa952693ddfdac7742a22',
    messagingSenderId: '285312235143',
    projectId: 'instagram-clone-flutter-2e127',
    authDomain: 'instagram-clone-flutter-2e127.firebaseapp.com',
    storageBucket: 'instagram-clone-flutter-2e127.firebasestorage.app',
    measurementId: 'G-GVGH8HK0XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpOoJWJhbPrphG1XsMALMejPvN1H6_wM',
    appId: '1:285312235143:android:501c5264f0a8a3f6742a22',
    messagingSenderId: '285312235143',
    projectId: 'instagram-clone-flutter-2e127',
    storageBucket: 'instagram-clone-flutter-2e127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iLGBhRKHcDCfZp86aJD-huS3I0qixq0',
    appId: '1:285312235143:ios:d2392d212aa798f1742a22',
    messagingSenderId: '285312235143',
    projectId: 'instagram-clone-flutter-2e127',
    storageBucket: 'instagram-clone-flutter-2e127.firebasestorage.app',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
